#! /usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

puts 'Custom installations for non winget apps'
puts ''

TEMP_WORKSPACE_NAME = 'temp-workspace'
FileUtils.rm_r(TEMP_WORKSPACE_NAME) if Dir.exist?(TEMP_WORKSPACE_NAME)
Dir.mkdir(TEMP_WORKSPACE_NAME)
Dir.chdir(TEMP_WORKSPACE_NAME)

custom_plans = Dir.children('../custom-installations')
custom_plans.each_with_index do |plan, index|
  print "#{index + 1} of #{custom_plans.length}: "
  require_relative "./custom-installations/#{plan}"
  puts ''
end
puts ''

Dir.chdir('..')

puts 'Stage 2 done.'
puts ''

puts 'Installation done.'
